/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import bean.ClienteMsl;
import dao.ClienteDAO;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import pesquisa.JDlgClientePesquisa;
import tools.Util;
import tools.UtilMsl;

/**
 *
 * @author u07679183120
 */
public class JDlgCliente extends javax.swing.JDialog {
private JDlgClientePesquisa jDlgClientePesquisa; 
    private boolean incl;
    MaskFormatter maskcpf;
    MaskFormatter maskrg;
    MaskFormatter masktelefone;
    MaskFormatter maskcep;
    UtilMsl util;

    public JDlgCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Cliente");
        setLocationRelativeTo(null);

        UtilMsl.habilitar(false,  jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil );
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        jBtnIncluir.setEnabled(true);
        
        
           try {
            maskcpf = new MaskFormatter("###.###.###-##");
            maskrg = new MaskFormatter("#.###.###");
            masktelefone = new MaskFormatter("(##)#####-####");
            maskcep = new MaskFormatter("#####-###");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jFmtTelefone.setFormatterFactory(new DefaultFormatterFactory(masktelefone));
        //jFmtRg.setFormatterFactory(new DefaultFormatterFactory(maskrg));
        //jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(maskcpf));
        //jTxtCep.setFormatterFactory(new DefaultFormatterFactory(maskcep));
    }

    public ClienteMsl viewBean() {
        ClienteMsl clienteMsl = new ClienteMsl();//set id
        int id = UtilMsl.strInt(jTxtCodigo.getText());//set id
        clienteMsl.setIdclienteMsl(id);//set id

        clienteMsl.setNomeMsl(jTxtNome.getText());//set texto
        clienteMsl.setSexoMsl(jTxtSexo.getText());//set texto
        clienteMsl.setRgMsl(jFmtRg.getText());//set texto
        clienteMsl.setCpfMsl(jFmtCpf.getText());//set texto
        
        Date nascimento = UtilMsl.strDate(jFmtNascimento.getText());//set data
        clienteMsl.setNascimentoMsl(nascimento);//set data
        
        clienteMsl.setEmailMsl(jTxtEmail.getText());//set texto
        clienteMsl.setTelefoneMsl(jTxtTelefone.getText());//set texto
        clienteMsl.setCelularMsl(jTxtCelular.getText());//set texto
        clienteMsl.setCepMsl(jTxtCep.getText());//set texto
        clienteMsl.setEnderecoMsl(jTxtEndereco.getText());//set texto
        clienteMsl.setBairroMsl(jTxtBairro.getText());//set texto
        clienteMsl.setCidadeMsl(jTxtCidade.getText());//set texto
        clienteMsl.setEstadoCivilMsl(jTxtCivil.getText());//set texto
        return clienteMsl;
    }
    
        public void beanView(ClienteMsl clienteMsl) {
        String intStr = UtilMsl.intStr(clienteMsl.getIdclienteMsl());//set id
        jTxtCodigo.setText(intStr);//set id
        
        jTxtNome.setText(clienteMsl.getNomeMsl());//set texto
        jTxtSexo.setText(clienteMsl.getSexoMsl());//set texto
        jFmtRg.setText(clienteMsl.getRgMsl());//set texto
        jFmtCpf.setText(clienteMsl.getCpfMsl());//set texto
        
        jFmtNascimento.setText(UtilMsl.dateStr(clienteMsl.getNascimentoMsl()));//set data
        
        jTxtEmail.setText(clienteMsl.getEmailMsl());//set texto
        jTxtTelefone.setText(clienteMsl.getTelefoneMsl());//set texto
        jTxtCelular.setText(clienteMsl.getCelularMsl());//set texto
        jTxtCep.setText(clienteMsl.getCepMsl());//set texto
        jTxtEndereco.setText(clienteMsl.getEnderecoMsl());//set texto
        jTxtBairro.setText(clienteMsl.getBairroMsl());//set texto
        jTxtCidade.setText(clienteMsl.getCidadeMsl());//set texto
        jTxtCivil.setText(clienteMsl.getEstadoCivilMsl());//set texto
        }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSobrenome = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTxtSexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFmtRg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jFmtCpf = new javax.swing.JTextField();
        jFmtNascimento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtTelefone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtCelular = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtCep = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxtEndereco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTxtBairro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTxtCidade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTxtCivil = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigoFocusLost(evt);
            }
        });
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 187, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 270, -1));

        jLabel3.setText("Sobrenome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));
        getContentPane().add(jTxtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 270, -1));

        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        jLabel9.setText("Sexo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTxtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, -1));

        jLabel10.setText("Rg");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        getContentPane().add(jFmtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, -1));

        jLabel11.setText("Cpf");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 270, -1));
        getContentPane().add(jFmtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 270, -1));

        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, -1));

        jLabel14.setText("Telefone");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 90, 20));
        getContentPane().add(jTxtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 270, 20));

        jLabel15.setText("Celular");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 100, 20));

        jTxtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCelularActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 270, 20));

        jLabel16.setText("Cep");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 20));
        getContentPane().add(jTxtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 270, 20));

        jLabel17.setText("Endereco");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 100, 20));

        jTxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 270, 20));

        jLabel18.setText("Bairro");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 20));
        getContentPane().add(jTxtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 270, 20));

        jLabel19.setText("Nascimento");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 100, 20));

        jTxtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 270, 20));

        jLabel20.setText("Estado Civil");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 80, 20));
        getContentPane().add(jTxtCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 270, 20));

        jLabel21.setText("Cidade");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        UtilMsl.habilitar(true,jBtnCancelar, jBtnConfirmar, jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        UtilMsl.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnExcluir,jBtnCancelar,jBtnConfirmar,jBtnAlterar,jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        

    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        UtilMsl.habilitar(true, jBtnCancelar,jBtnConfirmar, jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        UtilMsl.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
    if (UtilMsl.perguntar("Quer excluir?") == true) {
        ClienteMsl clienteMsl = viewBean();
        ClienteDAO clientesDAO = new ClienteDAO();
        clientesDAO.delete(clienteMsl);
        UtilMsl.mensagem("Excluido!");
        
    }else{
        UtilMsl.mensagem("Cancelado!");
    }
    UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
    
    }//GEN-LAST:event_jBtnExcluirActionPerformed


    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
    ClienteMsl clienteMsl = viewBean();
    ClienteDAO clientesDAO = new ClienteDAO();
    
    if (incl == true) {
        clientesDAO.insert(clienteMsl);
        UtilMsl.mensagem("Incluido com sucesso.");
    } else {
        clientesDAO.update(clienteMsl);
        UtilMsl.mensagem("Alterado com sucesso.");
        }
    
        UtilMsl.habilitar(false,jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        UtilMsl.habilitar(true, jBtnIncluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here: 
    jDlgClientePesquisa = new JDlgClientePesquisa(null, true);
    jDlgClientePesquisa.setTitle("Pesquisar");
    jDlgClientePesquisa.setTelaAnterior(this);
    jDlgClientePesquisa.setVisible(true);
    UtilMsl.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnIncluir);
    UtilMsl.habilitar(false, jBtnCancelar, jBtnConfirmar);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        UtilMsl.habilitar(false,jBtnCancelar, jBtnConfirmar, jBtnAlterar, jBtnExcluir, jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        UtilMsl.habilitar(true, jBtnIncluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigo, jTxtNome, jTxtSobrenome, jTxtSexo,jFmtRg,jFmtCpf,jFmtNascimento,jTxtEmail,jTxtTelefone,jTxtCelular,jTxtCep,jTxtEndereco,jTxtBairro,jTxtCidade,jTxtCivil);
        UtilMsl.mensagem("Cancelado");
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jTxtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoFocusLost

    private void jTxtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSexoActionPerformed

    private void jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpfActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jTxtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCelularActionPerformed

    private void jTxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEnderecoActionPerformed

    private void jTxtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCliente dialog = new JDlgCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JTextField jFmtCpf;
    private javax.swing.JTextField jFmtNascimento;
    private javax.swing.JTextField jFmtRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCelular;
    private javax.swing.JTextField jTxtCep;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtCivil;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtEstadoCivil;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtSexo;
    private javax.swing.JTextField jTxtSobrenome;
    private javax.swing.JTextField jTxtTelefone;
    // End of variables declaration//GEN-END:variables

 
}
