package bean;
// Generated 10/11/2023 12:38:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteMsl generated by hbm2java
 */
@Entity
@Table(name="cliente_msl"
    ,catalog="db_mario_lira"
)
public class ClienteMsl  implements java.io.Serializable {


     private int idclienteMsl;
     private String nomeMsl;
     private String sobrenomeMsl;
     private String sexoMsl;
     private String rgMsl;
     private String cpfMsl;
     private Date nascimentoMsl;
     private String emailMsl;
     private String telefoneMsl;
     private String celularMsl;
     private String cepMsl;
     private String enderecoMsl;
     private String bairroMsl;
     private String cidadeMsl;
     private String estadoCivilMsl;

    public ClienteMsl() {
    }

    public ClienteMsl(int idclienteMsl, String nomeMsl, String sobrenomeMsl, String sexoMsl, String rgMsl, String cpfMsl, Date nascimentoMsl, String emailMsl, String telefoneMsl, String celularMsl, String cepMsl, String enderecoMsl, String bairroMsl, String cidadeMsl, String estadoCivilMsl) {
       this.idclienteMsl = idclienteMsl;
       this.nomeMsl = nomeMsl;
       this.sobrenomeMsl = sobrenomeMsl;
       this.sexoMsl = sexoMsl;
       this.rgMsl = rgMsl;
       this.cpfMsl = cpfMsl;
       this.nascimentoMsl = nascimentoMsl;
       this.emailMsl = emailMsl;
       this.telefoneMsl = telefoneMsl;
       this.celularMsl = celularMsl;
       this.cepMsl = cepMsl;
       this.enderecoMsl = enderecoMsl;
       this.bairroMsl = bairroMsl;
       this.cidadeMsl = cidadeMsl;
       this.estadoCivilMsl = estadoCivilMsl;
    }
   
     @Id 

    
    @Column(name="idcliente_msl", unique=true, nullable=false)
    public int getIdclienteMsl() {
        return this.idclienteMsl;
    }
    
    public void setIdclienteMsl(int idclienteMsl) {
        this.idclienteMsl = idclienteMsl;
    }

    
    @Column(name="nome_msl", nullable=false, length=45)
    public String getNomeMsl() {
        return this.nomeMsl;
    }
    
    public void setNomeMsl(String nomeMsl) {
        this.nomeMsl = nomeMsl;
    }

    
    @Column(name="sobrenome_msl", nullable=false, length=45)
    public String getSobrenomeMsl() {
        return this.sobrenomeMsl;
    }
    
    public void setSobrenomeMsl(String sobrenomeMsl) {
        this.sobrenomeMsl = sobrenomeMsl;
    }

    
    @Column(name="sexo_msl", nullable=false, length=45)
    public String getSexoMsl() {
        return this.sexoMsl;
    }
    
    public void setSexoMsl(String sexoMsl) {
        this.sexoMsl = sexoMsl;
    }

    
    @Column(name="rg_msl", nullable=false, length=45)
    public String getRgMsl() {
        return this.rgMsl;
    }
    
    public void setRgMsl(String rgMsl) {
        this.rgMsl = rgMsl;
    }

    
    @Column(name="cpf_msl", nullable=false, length=45)
    public String getCpfMsl() {
        return this.cpfMsl;
    }
    
    public void setCpfMsl(String cpfMsl) {
        this.cpfMsl = cpfMsl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nascimento_msl", nullable=false, length=10)
    public Date getNascimentoMsl() {
        return this.nascimentoMsl;
    }
    
    public void setNascimentoMsl(Date nascimentoMsl) {
        this.nascimentoMsl = nascimentoMsl;
    }

    
    @Column(name="email_msl", nullable=false, length=45)
    public String getEmailMsl() {
        return this.emailMsl;
    }
    
    public void setEmailMsl(String emailMsl) {
        this.emailMsl = emailMsl;
    }

    
    @Column(name="telefone_msl", nullable=false, length=45)
    public String getTelefoneMsl() {
        return this.telefoneMsl;
    }
    
    public void setTelefoneMsl(String telefoneMsl) {
        this.telefoneMsl = telefoneMsl;
    }

    
    @Column(name="celular_msl", nullable=false, length=45)
    public String getCelularMsl() {
        return this.celularMsl;
    }
    
    public void setCelularMsl(String celularMsl) {
        this.celularMsl = celularMsl;
    }

    
    @Column(name="cep_msl", nullable=false, length=45)
    public String getCepMsl() {
        return this.cepMsl;
    }
    
    public void setCepMsl(String cepMsl) {
        this.cepMsl = cepMsl;
    }

    
    @Column(name="endereco_msl", nullable=false, length=45)
    public String getEnderecoMsl() {
        return this.enderecoMsl;
    }
    
    public void setEnderecoMsl(String enderecoMsl) {
        this.enderecoMsl = enderecoMsl;
    }

    
    @Column(name="bairro_msl", nullable=false, length=45)
    public String getBairroMsl() {
        return this.bairroMsl;
    }
    
    public void setBairroMsl(String bairroMsl) {
        this.bairroMsl = bairroMsl;
    }

    
    @Column(name="cidade_msl", nullable=false, length=45)
    public String getCidadeMsl() {
        return this.cidadeMsl;
    }
    
    public void setCidadeMsl(String cidadeMsl) {
        this.cidadeMsl = cidadeMsl;
    }

    
    @Column(name="estadoCivil_msl", nullable=false, length=45)
    public String getEstadoCivilMsl() {
        return this.estadoCivilMsl;
    }
    
    public void setEstadoCivilMsl(String estadoCivilMsl) {
        this.estadoCivilMsl = estadoCivilMsl;
    }




}


