package bean;
// Generated 10/11/2023 12:38:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FuncionarioMsl generated by hbm2java
 */
@Entity
@Table(name="funcionario_msl"
    ,catalog="db_mario_lira"
)
public class FuncionarioMsl  implements java.io.Serializable {


     private int idfuncionarioMsl;
     private String nomeMsl;
     private String enderecoMsl;
     private String emailMsl;
     private String telefoneMsl;
     private String informacoesMsl;

    public FuncionarioMsl() {
    }

    public FuncionarioMsl(int idfuncionarioMsl, String nomeMsl, String enderecoMsl, String emailMsl, String telefoneMsl, String informacoesMsl) {
       this.idfuncionarioMsl = idfuncionarioMsl;
       this.nomeMsl = nomeMsl;
       this.enderecoMsl = enderecoMsl;
       this.emailMsl = emailMsl;
       this.telefoneMsl = telefoneMsl;
       this.informacoesMsl = informacoesMsl;
    }
   
     @Id 

    
    @Column(name="idfuncionario_msl", unique=true, nullable=false)
    public int getIdfuncionarioMsl() {
        return this.idfuncionarioMsl;
    }
    
    public void setIdfuncionarioMsl(int idfuncionarioMsl) {
        this.idfuncionarioMsl = idfuncionarioMsl;
    }

    
    @Column(name="nome_msl", nullable=false, length=45)
    public String getNomeMsl() {
        return this.nomeMsl;
    }
    
    public void setNomeMsl(String nomeMsl) {
        this.nomeMsl = nomeMsl;
    }

    
    @Column(name="endereco_msl", nullable=false, length=45)
    public String getEnderecoMsl() {
        return this.enderecoMsl;
    }
    
    public void setEnderecoMsl(String enderecoMsl) {
        this.enderecoMsl = enderecoMsl;
    }

    
    @Column(name="email_msl", nullable=false, length=45)
    public String getEmailMsl() {
        return this.emailMsl;
    }
    
    public void setEmailMsl(String emailMsl) {
        this.emailMsl = emailMsl;
    }

    
    @Column(name="telefone_msl", nullable=false, length=45)
    public String getTelefoneMsl() {
        return this.telefoneMsl;
    }
    
    public void setTelefoneMsl(String telefoneMsl) {
        this.telefoneMsl = telefoneMsl;
    }

    
    @Column(name="informacoes_msl", nullable=false, length=45)
    public String getInformacoesMsl() {
        return this.informacoesMsl;
    }
    
    public void setInformacoesMsl(String informacoesMsl) {
        this.informacoesMsl = informacoesMsl;
    }




}


