package bean;
// Generated 10/11/2023 12:38:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JogosMsl generated by hbm2java
 */
@Entity
@Table(name="jogos_msl"
    ,catalog="db_mario_lira"
)
public class JogosMsl  implements java.io.Serializable {


     private int idjogosMsl;
     private String nomeMsl;
     private String plataformaMsl;
     private String tipoDeJogoMsl;
     private String classificacaoIndicativaMsl;
     private String numeroDeJogadoresMsl;
     private double valorMsl;
     private String codigoDoJogoMsl;
     
    public JogosMsl() {
    }

	
    public JogosMsl(int idjogosMsl, String nomeMsl, String plataformaMsl, String tipoDeJogoMsl, String classificacaoIndicativaMsl, String numeroDeJogadoresMsl, double valorMsl, String codigoDoJogoMsl) {
        this.idjogosMsl = idjogosMsl;
        this.nomeMsl = nomeMsl;
        this.plataformaMsl = plataformaMsl;
        this.tipoDeJogoMsl = tipoDeJogoMsl;
        this.classificacaoIndicativaMsl = classificacaoIndicativaMsl;
        this.numeroDeJogadoresMsl = numeroDeJogadoresMsl;
        this.valorMsl = valorMsl;
        this.codigoDoJogoMsl = codigoDoJogoMsl;
    }
    public JogosMsl(int idjogosMsl, String nomeMsl, String plataformaMsl, String tipoDeJogoMsl, String classificacaoIndicativaMsl, String numeroDeJogadoresMsl, double valorMsl, String codigoDoJogoMsl, Set vendaJogoMsls) {
       this.idjogosMsl = idjogosMsl;
       this.nomeMsl = nomeMsl;
       this.plataformaMsl = plataformaMsl;
       this.tipoDeJogoMsl = tipoDeJogoMsl;
       this.classificacaoIndicativaMsl = classificacaoIndicativaMsl;
       this.numeroDeJogadoresMsl = numeroDeJogadoresMsl;
       this.valorMsl = valorMsl;
       this.codigoDoJogoMsl = codigoDoJogoMsl;
  
    }
   
     @Id 

    
    @Column(name="idjogos_msl", unique=true, nullable=false)
    public int getIdjogosMsl() {
        return this.idjogosMsl;
    }
    
    public void setIdjogosMsl(int idjogosMsl) {
        this.idjogosMsl = idjogosMsl;
    }

    
    @Column(name="nome_msl", nullable=false, length=45)
    public String getNomeMsl() {
        return this.nomeMsl;
    }
    
    public void setNomeMsl(String nomeMsl) {
        this.nomeMsl = nomeMsl;
    }

    
    @Column(name="plataforma_msl", nullable=false, length=45)
    public String getPlataformaMsl() {
        return this.plataformaMsl;
    }
    
    public void setPlataformaMsl(String plataformaMsl) {
        this.plataformaMsl = plataformaMsl;
    }

    
    @Column(name="tipoDeJogo_msl", nullable=false, length=45)
    public String getTipoDeJogoMsl() {
        return this.tipoDeJogoMsl;
    }
    
    public void setTipoDeJogoMsl(String tipoDeJogoMsl) {
        this.tipoDeJogoMsl = tipoDeJogoMsl;
    }

    
    @Column(name="classificacaoIndicativa_msl", nullable=false, length=45)
    public String getClassificacaoIndicativaMsl() {
        return this.classificacaoIndicativaMsl;
    }
    
    public void setClassificacaoIndicativaMsl(String classificacaoIndicativaMsl) {
        this.classificacaoIndicativaMsl = classificacaoIndicativaMsl;
    }

    
    @Column(name="numeroDeJogadores_msl", nullable=false, length=45)
    public String getNumeroDeJogadoresMsl() {
        return this.numeroDeJogadoresMsl;
    }
    
    public void setNumeroDeJogadoresMsl(String numeroDeJogadoresMsl) {
        this.numeroDeJogadoresMsl = numeroDeJogadoresMsl;
    }

    
    @Column(name="valor_msl", nullable=false, precision=10)
    public double getValorMsl() {
        return this.valorMsl;
    }
    
    public void setValorMsl(double valorMsl) {
        this.valorMsl = valorMsl;
    }

    
    @Column(name="codigoDoJogo_msl", nullable=false, length=45)
    public String getCodigoDoJogoMsl() {
        return this.codigoDoJogoMsl;
    }
    
    public void setCodigoDoJogoMsl(String codigoDoJogoMsl) {
        this.codigoDoJogoMsl = codigoDoJogoMsl;
    }






}


