package bean;
// Generated 10/11/2023 12:38:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosMsl generated by hbm2java
 */
@Entity
@Table(name="usuarios_msl"
    ,catalog="db_mario_lira"
)
public class UsuariosMsl  implements java.io.Serializable {


     private int idusuariosMsl;
     private String nomeMsl;
     private String apelidoMsl;
     private String cpfMsl;
     private Date dataNascimentoMsl;
     private String senhaMsl;
     private int nivelMsl;
     private String ativoMsl;

    public UsuariosMsl() {
    }

    public UsuariosMsl(int idusuariosMsl, String nomeMsl, String apelidoMsl, String cpfMsl, Date dataNascimentoMsl, String senhaMsl, int nivelMsl, String ativoMsl) {
       this.idusuariosMsl = idusuariosMsl;
       this.nomeMsl = nomeMsl;
       this.apelidoMsl = apelidoMsl;
       this.cpfMsl = cpfMsl;
       this.dataNascimentoMsl = dataNascimentoMsl;
       this.senhaMsl = senhaMsl;
       this.nivelMsl = nivelMsl;
       this.ativoMsl = ativoMsl;
    }
   
     @Id 

    
    @Column(name="idusuarios_msl", unique=true, nullable=false)
    public int getIdusuariosMsl() {
        return this.idusuariosMsl;
    }
    
    public void setIdusuariosMsl(int idusuariosMsl) {
        this.idusuariosMsl = idusuariosMsl;
    }

    
    @Column(name="nome_msl", nullable=false, length=45)
    public String getNomeMsl() {
        return this.nomeMsl;
    }
    
    public void setNomeMsl(String nomeMsl) {
        this.nomeMsl = nomeMsl;
    }

    
    @Column(name="apelido_msl", nullable=false, length=45)
    public String getApelidoMsl() {
        return this.apelidoMsl;
    }
    
    public void setApelidoMsl(String apelidoMsl) {
        this.apelidoMsl = apelidoMsl;
    }

    
    @Column(name="cpf_msl", nullable=false, length=45)
    public String getCpfMsl() {
        return this.cpfMsl;
    }
    
    public void setCpfMsl(String cpfMsl) {
        this.cpfMsl = cpfMsl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_msl", nullable=false, length=10)
    public Date getDataNascimentoMsl() {
        return this.dataNascimentoMsl;
    }
    
    public void setDataNascimentoMsl(Date dataNascimentoMsl) {
        this.dataNascimentoMsl = dataNascimentoMsl;
    }

    
    @Column(name="senha_msl", nullable=false, length=10)
    public String getSenhaMsl() {
        return this.senhaMsl;
    }
    
    public void setSenhaMsl(String senhaMsl) {
        this.senhaMsl = senhaMsl;
    }

    
    @Column(name="nivel_msl", nullable=false)
    public int getNivelMsl() {
        return this.nivelMsl;
    }
    
    public void setNivelMsl(int nivelMsl) {
        this.nivelMsl = nivelMsl;
    }

    
    @Column(name="Ativo_msl", nullable=false, length=20)
    public String getAtivoMsl() {
        return this.ativoMsl;
    }
    
    public void setAtivoMsl(String ativoMsl) {
        this.ativoMsl = ativoMsl;
    }




}


