package bean;
// Generated 10/11/2023 12:38:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaJogoMsl generated by hbm2java
 */
@Entity
@Table(name="venda_jogo_msl"
    ,catalog="db_mario_lira"
)
public class VendaJogoMsl  implements java.io.Serializable {


     private int idvendaJogoMsl;
     private JogosMsl jogosMsl;
     private VendaMsl vendaMsl;
     private String quantidadeMsl;
     private String confirmadoMsl;
     private String codigoDoJogoMsl;

    public VendaJogoMsl() {
    }

    public VendaJogoMsl(int idvendaJogoMsl, JogosMsl jogosMsl, VendaMsl vendaMsl, String quantidadeMsl, String confirmadoMsl, String codigoDoJogoMsl) {
       this.idvendaJogoMsl = idvendaJogoMsl;
       this.jogosMsl = jogosMsl;
       this.vendaMsl = vendaMsl;
       this.quantidadeMsl = quantidadeMsl;
       this.confirmadoMsl = confirmadoMsl;
       this.codigoDoJogoMsl = codigoDoJogoMsl;
    }
   
     @Id 

    
    @Column(name="idvenda_jogo_msl", unique=true, nullable=false)
    public int getIdvendaJogoMsl() {
        return this.idvendaJogoMsl;
    }
    
    public void setIdvendaJogoMsl(int idvendaJogoMsl) {
        this.idvendaJogoMsl = idvendaJogoMsl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_jogos_msl", nullable=false)
    public JogosMsl getJogosMsl() {
        return this.jogosMsl;
    }
    
    public void setJogosMsl(JogosMsl jogosMsl) {
        this.jogosMsl = jogosMsl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_venda_msl", nullable=false)
    public VendaMsl getVendaMsl() {
        return this.vendaMsl;
    }
    
    public void setVendaMsl(VendaMsl vendaMsl) {
        this.vendaMsl = vendaMsl;
    }

    
    @Column(name="quantidade_msl", nullable=false, length=45)
    public String getQuantidadeMsl() {
        return this.quantidadeMsl;
    }
    
    public void setQuantidadeMsl(String quantidadeMsl) {
        this.quantidadeMsl = quantidadeMsl;
    }

    
    @Column(name="confirmado_msl", nullable=false, length=1)
    public String getConfirmadoMsl() {
        return this.confirmadoMsl;
    }
    
    public void setConfirmadoMsl(String confirmadoMsl) {
        this.confirmadoMsl = confirmadoMsl;
    }

    
    @Column(name="codigoDoJogo_msl", nullable=false, length=10)
    public String getCodigoDoJogoMsl() {
        return this.codigoDoJogoMsl;
    }
    
    public void setCodigoDoJogoMsl(String codigoDoJogoMsl) {
        this.codigoDoJogoMsl = codigoDoJogoMsl;
    }




}


