package bean;
// Generated 10/11/2023 12:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VendaMsl generated by hbm2java
 */
@Entity
@Table(name="venda_msl"
    ,catalog="db_mario_lira"
)
public class VendaMsl  implements java.io.Serializable {


     private int idvendaMsl;
     private String dataHoraMsl;
     private String enderecoMsl;
     private String vendedorMsl;
     private String vendaJogosMsl;
     private String vendaMslcol;
     

    public VendaMsl() {
    }

	
    public VendaMsl(int idvendaMsl, String dataHoraMsl, String enderecoMsl, String vendedorMsl, String vendaJogosMsl, String vendaMslcol) {
        this.idvendaMsl = idvendaMsl;
        this.dataHoraMsl = dataHoraMsl;
        this.enderecoMsl = enderecoMsl;
        this.vendedorMsl = vendedorMsl;
        this.vendaJogosMsl = vendaJogosMsl;
        this.vendaMslcol = vendaMslcol;
    }
    public VendaMsl(int idvendaMsl, String dataHoraMsl, String enderecoMsl, String vendedorMsl, String vendaJogosMsl, String vendaMslcol, Set vendaJogoMsls) {
       this.idvendaMsl = idvendaMsl;
       this.dataHoraMsl = dataHoraMsl;
       this.enderecoMsl = enderecoMsl;
       this.vendedorMsl = vendedorMsl;
       this.vendaJogosMsl = vendaJogosMsl;
       this.vendaMslcol = vendaMslcol;
 
    }
   
     @Id 

    
    @Column(name="idvenda_msl", unique=true, nullable=false)
    public int getIdvendaMsl() {
        return this.idvendaMsl;
    }
    
    public void setIdvendaMsl(int idvendaMsl) {
        this.idvendaMsl = idvendaMsl;
    }

    
    @Column(name="dataHora_msl", nullable=false, length=45)
    public String getDataHoraMsl() {
        return this.dataHoraMsl;
    }
    
    public void setDataHoraMsl(String dataHoraMsl) {
        this.dataHoraMsl = dataHoraMsl;
    }

    
    @Column(name="endereco_msl", nullable=false, length=45)
    public String getEnderecoMsl() {
        return this.enderecoMsl;
    }
    
    public void setEnderecoMsl(String enderecoMsl) {
        this.enderecoMsl = enderecoMsl;
    }

    
    @Column(name="vendedor_msl", nullable=false, length=45)
    public String getVendedorMsl() {
        return this.vendedorMsl;
    }
    
    public void setVendedorMsl(String vendedorMsl) {
        this.vendedorMsl = vendedorMsl;
    }

    
    @Column(name="venda_jogos_msl", nullable=false, length=45)
    public String getVendaJogosMsl() {
        return this.vendaJogosMsl;
    }
    
    public void setVendaJogosMsl(String vendaJogosMsl) {
        this.vendaJogosMsl = vendaJogosMsl;
    }

    
    @Column(name="venda_mslcol", nullable=false, length=45)
    public String getVendaMslcol() {
        return this.vendaMslcol;
    }
    
    public void setVendaMslcol(String vendaMslcol) {
        this.vendaMslcol = vendaMslcol;
    }






}


